include/arachni/system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

include/arachni/system/arachni-ui-web/app/models/dispatcher.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

require 'arachni/rpc/client'

class Dispatcher < ActiveRecord::Base
    include Extensions::Notifier

    has_many :scans

    has_and_belongs_to_many :users
    belongs_to :owner, class_name: 'User', foreign_key: :owner_id

    validates_presence_of :address

    validates_presence_of :port
    validates_numericality_of :port

    validates_uniqueness_of :address, scope: :port, case_sensitive: false

    validate :server_reachability
    validate :validate_description

    before_save    :add_owner_to_subscribers
    before_destroy :delete_client

    after_create  DispatcherManager.instance

    serialize :statistics, Hash

    scope :alive,       -> { where alive: true }
    scope :unreachable, -> { where alive: false }
    scope :global,      -> { where global: true }

    # Exclude sensitive info.
    def to_json( options = {} )
        return super if options[:safe]

        stats = statistics.dup
        statistics['running_jobs'].each { |j| j.delete 'token' }
        super( options )
    ensure
        self.statistics = stats
    end

    def self.describe_notification( action )
        case action
            when :destroy
                'was deleted'
            when :create
                'created'
            when :update
                'was updated'
            when :share
                'was shared with you'
            when :make_default
                'was set as the system default'
            else
                action.to_s
        end
    end

    def self.preferred
        alive.order( 'score ASC' ).first
    end

    def family
        [self]
    end

    def self.default
        self.where( default: true ).first
    end

    def self.unmake_default
        update_all default: false
    end

    def make_default
        self.class.unmake_default
        self.default = true
        self.save
    end

    def default?
        !!self.default
    end

    def self.find_by_url( url )
        address, port = *url.split( ':' )
        where( address: address, port: port ).first
    end

    def self.grid_members
        all.select { |d| d.grid_member? }
    end

    def self.non_grid_members
        all.reject { |d| d.grid_member? }
    end

    def self.has_grid?
        alive.map { |d| d.grid_member? }.include? true
    end

    def self.recent( limit = 5 )
        limit( limit ).order( "id desc" )
    end

    def to_label
        str = to_s
        str << " | #{jobs.size} scans" if jobs.any?
        str << " | Pipe: #{pipe_id}" if !pipe_id.to_s.empty?
        str
    end

    def to_s
        str = ''
        str << "#{name} | " if !name.to_s.empty?
        str << "#{url}"
    end

    def has_scheduled_scans?
        scans.scheduled.any?
    end

    def grid_member?
        (statistics['neighbours'] || []).any?
    end

    def alive?
        !!alive
    end
    alias :reachable? :alive?

    def statistics
        { 'node' => {} }.merge( super || {})
    end

    def consumed_pids
        statistics['consumed_pids'] || []
    end

    def name
        statistics['node']['nickname']
    end

    def pipe_id
        statistics['node']['pipe_id']
    end

    def neighbours
        (statistics['neighbours'] || []).map { |n| Dispatcher.find_by_url( n ) }
    end

    def weight
        statistics['node']['weight']
    end

    def jobs
        statistics['running_jobs'] || []
    end

    def finished_jobs
        statistics['finished_jobs'] || []
    end

    def node_info
        statistics['node']
    end

    def snapshots
        statistics['snapshots'] || []
    end

    def snapshot_filenames
        snapshots.map { |s| File.basename s }
    end

    def url
        "#{address}:#{port}"
    end

    def client
        client_synchronize do
            client_factory[client_key] ||=
                Arachni::RPC::Client::Dispatcher.new(
                    Arachni::Options.instance, url
                )
        end
    end

    def refresh( &block )
        Rails.logger.info "#{self.class}##{__method__}: #{self.id}"
        client.statistics do |stats|
            if stats.rpc_exception?
                if alive?
                    self.alive = false
                    save( validate: false )
                end

                delete_client
                block.call if block_given?
                next
            end

            # Skip validation because #server_reachability is not necessary.
            self.alive      = true
            self.statistics = stats
            self.score      = stats['node']['score']
            save( validate: false )

            stats['neighbours'].each do |neighbour|
                naddress, nport = neighbour.split( ':' )
                next if self.class.where( address: naddress, port: nport ).any?
                self.class.create( address: naddress, port: nport, owner_id: owner_id,
                                   description: "Automatically added as a neighbour of '#{url}'." )
            end

            block.call if block_given?
        end
    end

    private

    def client_factory
        @@dispatchers ||= {}
    end

    def client_synchronize( &block )
        (@@client_mutex ||= Mutex.new).synchronize(&block)
    end

    def client_key
        url.hash
    end

    def delete_client
        client_synchronize do
            i = client_factory.delete( client_key )
            i.close if i
        end
    end

    def server_reachability
        return if ApplicationHelper.host_reachable?( address, port )

        err = 'does not point to a running server'
        errors.add :address, err
        errors.add :port, err
    end

    def validate_description
        return if ActionController::Base.helpers.strip_tags( description ) == description
        errors.add :description, 'cannot contain HTML, please use Markdown instead'
    end

    def add_owner_to_subscribers
        return if !owner
        self.user_ids |= [owner.id]
        true
    end

end

include/arachni/system/arachni-ui-web/app/controllers/dispatchers_controller.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class DispatchersController < ApplicationController
    include ApplicationHelper
    include NotificationsHelper
    include DispatchersHelper

    before_filter :authenticate_user!
    before_filter :new_dispatcher, only: [ :create ]

    load_and_authorize_resource

    # GET /dispatchers
    # GET /dispatchers.json
    def index
        prepare_table_data

        html_block = if render_partial?
                         proc { render partial: 'tables' }
                     end

        respond_to do |format|
            format.html( &html_block )
            format.js { render '_tables.js' }
            format.json { render json: @dispatchers }
        end
    end

    # GET /dispatchers/1
    # GET /dispatchers/1.json
    def show
        @dispatcher = Dispatcher.find( params.require( :id ) )

        html_block = if render_partial?
                         proc { render @dispatcher }
                     end

        respond_to do |format|
            format.html( &html_block )
            format.json { render json: @dispatcher }
        end
    end

    # GET /dispatchers/new
    # GET /dispatchers/new.json
    def new
        @dispatcher = Dispatcher.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @dispatcher }
        end
    end

    # GET /dispatchers/1/edit
    def edit
        @dispatcher = Dispatcher.find( params.require( :id ) )
    end

    # POST /dispatchers
    # POST /dispatchers.json
    def create
        @dispatcher.owner = current_user

        respond_to do |format|
            if @dispatcher.save
                notify @dispatcher

                format.html do
                    redirect_to @dispatcher,
                                notice: 'Dispatcher was successfully created and ' +
                                    'will be available shortly.'
                end
                format.json { render json: @dispatcher, status: :created, location: @dispatcher }
            else
                format.html { render action: "new" }
                format.json { render json: @dispatcher.errors, status: :unprocessable_entity }
            end
        end
    end

    # PUT /profiles/1/make_default
    def make_default
        dispatcher = Dispatcher.find( params.require( :id ) )

        fail 'Cannot make a non-global dispatcher the default one.' if !dispatcher.global?

        dispatcher.make_default
        params.delete( :id )

        notify dispatcher

        prepare_table_data
        render partial: 'tables', formats: :js
    end

    # PUT /dispatchers/1
    # PUT /dispatchers/1.json
    def update
        @dispatcher = Dispatcher.find( params.require( :id ) )

        respond_to do |format|
            if @dispatcher.update_attributes( strong_params )
                notify @dispatcher

                format.html { redirect_to @dispatcher, notice: 'Dispatcher was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @dispatcher.errors, status: :unprocessable_entity }
            end
        end
    end

    def share
        @dispatcher = Dispatcher.find( params.require( :id ) )

        respond_to do |format|
            if @dispatcher.update_attributes( params.require( :dispatcher ).permit( user_ids: [] ) )
                notify @dispatcher

                format.html { redirect_to :back, notice: 'Dispatcher was successfully shared.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @dispatcher.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /dispatchers/1
    # DELETE /dispatchers/1.json
    def destroy
        @dispatcher = Dispatcher.find( params.require( :id ) )

        if @dispatcher.has_scheduled_scans?
            fail 'Cannot delete a Dispatcher assigned to scheduled Scans.'
        end

        notify @dispatcher

        @dispatcher.destroy

        respond_to do |format|
            format.html { redirect_to dispatchers_url }
            format.json { head :no_content }
        end
    end

    private

    def new_dispatcher
        @dispatcher = Dispatcher.new( strong_params )
    end

    def strong_params
        allowed = [ :address, :port, :description, { user_ids: [] } ]
        allowed << :global if current_user.admin?

        params.require( :dispatcher ).permit( *allowed )
    end

    def prepare_table_data
        params[:alive_tab] ||= params[:unreachable_tab] ||= 'yours'

        @counts = {
            alive:       {},
            unreachable: {}
        }
        %w(yours shared others global).each do |type|
            begin
                @counts[:alive][type] = dispatcher_filter( type ).alive.count

                @counts[:alive]['total'] ||= 0
                @counts[:alive]['total']  += @counts[:alive][type]

                @counts[:unreachable][type] = dispatcher_filter( type ).unreachable.count

                @counts[:unreachable]['total'] ||= 0
                @counts[:unreachable]['total']  += @counts[:unreachable][type]
            rescue
            end
        end

        @alive_dispatchers = dispatcher_filter( params[:alive_tab] ).
            page( params[:page] ).
            per( HardSettings.dispatcher_pagination_entries ).
            alive.
            order( 'id DESC' )

        @unreachable_dispatchers = dispatcher_filter( params[:unreachable_tab] ).
            page( params[:page] ).
            per( HardSettings.dispatcher_pagination_entries ).
            unreachable.
            order( 'id DESC' )
    end

end

include/arachni/system/arachni-ui-web/app/helpers/dispatchers_helper.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module DispatchersHelper

    def dispatcher_filter( filter )
        filter ||= 'yours'

        case filter
            when 'yours'
                current_user.own_dispatchers
            when 'shared'
                current_user.shared_dispatchers
            when 'global'
                Dispatcher.global

            when 'others'
                raise 'Unauthorised!' if !current_user.admin?
                current_user.others_dispatchers
        end
    end

end

include/arachni/system/arachni-ui-web/app/views/dispatchers/_dispatcher.html.erb
<% if !@dispatcher.reachable? %>
    <p class="alert alert-warning">
        This Dispatcher could not be reached, the data displayed here are
        from when it was last available and will most likely be out of date.
    </p>
<% end %>

<div class="row-fluid">
    <div class="span10">
        <div class="page-header">
            <h1><%= @dispatcher.url %></h1>
            <% if !@dispatcher.description.to_s.empty? %>
                <div class="lead"><%= m @dispatcher.description %></div>
            <% end %>
        </div>
    </div>
    <div class="span2">
        <% if @dispatcher.global? %>
            <p class="label label-info">
                Global
            </p>
        <% end %>

        <% if can? :edit, @dispatcher %>
            <%= link_to edit_dispatcher_path( @dispatcher ), title: 'Edit Dispatcher',
                        class: 'btn btn-small btn-warning' do %>
                <i class="icon-pencil"></i>
            <% end %>
        <% end %>

        <% if can? :delete, @dispatcher %>
            <%= link_to @dispatcher, title: 'Delete Dispatcher',
                        method: :delete, class: 'btn btn-small btn-danger',
                        data: { confirm: 'Are you sure you want to delete this Dispatcher?' } do %>
                <i class="icon-trash"></i>
            <% end %>
        <% end %>
    </div>
</div>

<div id="node-info">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Name</th>

            <th>
                Workload score

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="Signifies the Dispatcher's workload.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>

            <th>
                Pipe-ID

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="Identification for the bandwidth pipe to which
                   the Dispatcher is connected.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>

            <th>Grid member?</th>

            <% if @dispatcher.grid_member? %>
                <th>Neighbours</th>
            <% end %>

            <th class="hidden-phone">
                Desired pool size

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="Amount of Instances which should be available
                   for dispatch at any given moment.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>
            <th class="hidden-phone">
                Current pool size

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="Amount of Instances which are available for dispatch.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>
            <th class="hidden-phone">
                Consumed PIDs

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="OS process IDs used up by the Dispatcher.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>
        </tr>
        </thead>
        <tr>
            <td><%= @dispatcher.name || '(Not set)' %></td>
            <td><%= @dispatcher.score %></td>
            <td><%= @dispatcher.pipe_id || '(Not set)' %></td>
            <td><%= @dispatcher.grid_member? ? 'Yes' : 'No' %></td>

            <% if @dispatcher.grid_member? %>
                <td>
                    <% @dispatcher.neighbours.map do |neighbour| %>
                        <%= link_to neighbour, dispatcher_path( neighbour )%>
                    <% end.join( ', ' ) %>
                </td>
            <% end %>

            <td class="hidden-phone"><%= @dispatcher.statistics['init_pool_size'] %></td>
            <td class="hidden-phone"><%= @dispatcher.statistics['curr_pool_size'] %></td>
            <td class="hidden-phone"><%= @dispatcher.consumed_pids.join( ', ' ) %></td>
        </tr>
    </table>
</div>

<h2>Instances</h2>
<div id="proc-tables">
    <%= render partial: 'proc_tables', locals: { dispatcher: @dispatcher.finished_jobs } %>
</div>

include/arachni/system/arachni-ui-web/app/views/dispatchers/_form.html.erb
<%= simple_form_for( @dispatcher ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <div class="row-fluid">
            <div class="span6">
                <div class="row-fluid">
                    <div class="span6">
                        <%= f.input :address, label: false, placeholder: 'Address' %>
                    </div>
                    <div class="span6">
                        <%= f.input :port, label: false, placeholder: 'Port' %>
                    </div>
                </div>

                <div class="row-fluid">
                    <div class="span12">
                        <%= f.input :description, label: false, placeholder: 'Description',
                                    hint: 'You can use Markdown for text formatting.' %>
                    </div>
                </div>
            </div>

            <div class="span6">
                <% if can? :make_default, @dispatcher %>
                    <div class="row-fluid">
                        <div class="span12">
                            <%= f.input :global %>
                            <p class="help-block">
                                Make this dispatcher globally available.
                            </p>
                        </div>
                    </div>
                <% end %>

                <div class="row-fluid">
                    <div class="span12">
                        <%= f.association :users, label: 'Share with:',
                                          collection: User.all - [current_user] %>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-actions">
        <%= f.button :submit %>
    </div>
<% end %>

include/arachni/system/arachni-ui-web/app/views/dispatchers/_table.html.erb
<%
   treat_as_alive = local_assigns[:treat_as_alive].nil? ? true : false
   type = (treat_as_alive ? :alive : :unreachable)

   tab_name   = "#{type}_tab"
   active_tab = params["#{type}_tab"]
   opts       = params.dup
   opts.delete( :format )
%>

<ul class="nav nav-tabs" id="profile-table-tab"
    data-table-container="table-container">

    <% if @counts[type]['yours'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-user"></i>
                Yours <small>[<%= @counts[type]['yours'] %>]</small>
            </a>
        </li>
    <% else %>
        <li
        <% if active_tab == 'yours' %>
        class="active"
        <% end %>
        >

            <%= link_to dispatchers_path( opts.merge( tab_name => 'yours' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-user"></i>
                Yours <small>[<%= @counts[type]['yours'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if @counts[type]['shared'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-share-alt"></i>
                Shared <small>[<%= @counts[type]['shared'] %>]</small>
            </a>
        </li>
    <% else %>

        <li
        <% if active_tab == 'shared' %>
        class="active"
        <% end %>

        >
            <%= link_to dispatchers_path( opts.merge( tab_name => 'shared' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-share-alt"></i>
                Shared <small>[<%= @counts[type]['shared'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if @counts[type]['global'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-globe"></i>
                Global <small>[<%= @counts[type]['global'] %>]</small>
            </a>
        </li>
    <% else %>
        <li
        <% if active_tab == 'global' %>
        class="active"
        <% end %>
        >
            <%= link_to dispatchers_path( opts.merge( tab_name => 'global' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-globe"></i>
                Global <small>[<%= @counts[type]['global'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if current_user.admin? %>
        <% if @counts[type]['others'] == 0 %>
            <li class="disabled">
                <a href="#">
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts[type]['others'] %>]</small>
                </a>
            </li>
        <% else %>
            <li
            <% if active_tab == 'others' %>
            class="active"
            <% end %>
            >
                <%= link_to dispatchers_path( opts.merge( tab_name => 'others' ) ),
                            onclick: 'loading();', remote: true do %>
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts[type]['others'] %>]</small>
                <% end %>
            </li>
        <% end %>
    <% end %>

</ul>

<p class="muted">
    <%=
        case active_tab
            when 'yours'
                "You are seeing dispatchers you've created."
            when 'shared'
                "You are seeing dispatchers others have shared with you."
            when 'global'
                "You are seeing globally available dispatchers."
            when 'others'
                "You are seeing all others' dispatchers -- you can see them because you're an administrator."
        end
    %>
</p>

<% if dispatchers.any? %>
    <table class="table table-striped table-hover table-condensed">
        <thead>
        <tr>
            <% if treat_as_alive && active_tab == 'global' %>
                <th>
                    Default?
                </th>
            <% end %>

            <th>URL</th>
            <th>
                Workload score

                <a href="#" rel="tooltip" data-placement="bottom"
                   title="Signifies the Dispatcher's scan workload.">
                    <i class="icon-info-sign"></i>
                </a>
            </th>

            <% if treat_as_alive %>
                <th>Alive Instances</th>
                <th>Name</th>
                <th>
                    Pipe-ID

                    <a href="#" rel="tooltip" data-placement="bottom"
                       title="Identification for the bandwidth pipe to which
                   the Dispatcher is connected.">
                        <i class="icon-info-sign"></i>
                    </a>
                </th>
                <th>Grid member?</th>
            <% end %>

            <th>Description</th>
            <th></th>
        </tr>
        </thead>

        <% dispatchers.each do |dispatcher| %>
            <tr>
                <% if treat_as_alive && active_tab == 'global' %>
                    <td>
                        <%= simple_form_for dispatcher,
                                            url: make_default_dispatcher_path( dispatcher, opts ),
                                            method: :patch, remote: true,
                                            html: { onsubmit: 'loading();' } do %>
                            <input type="radio"
                                   class="make-default"
                                   onclick="$(this).submit()"
                                   <%= 'checked="checked"'.html_safe if dispatcher.default? %>
                                   <%= 'disabled' if !current_user.admin? %>
                            >
                        <% end %>
                    </td>
                <% end %>

                <td><%= dispatcher.url %></td>
                <td><%= dispatcher.score %></td>

                <% if treat_as_alive %>
                    <td><%= (ss = dispatcher.jobs.size) > 1 ? ss : 'None yet' %></td>
                    <td><%= dispatcher.name || '(Not set)' %></td>
                    <td><%= dispatcher.pipe_id || '(Not set)' %></td>
                    <td><%= dispatcher.grid_member? ? 'Yes' : 'No' %></td>
                <% end %>

                <td><%= truncate_html m dispatcher.description %></td>

                <td>
                    <% if can? :read, Dispatcher %>
                        <%= link_to dispatcher, title: 'Show Dispatcher info',
                                    class: 'btn btn-small btn-info' do %>
                            <i class="icon-eye-open"></i>
                        <% end %>
                    <% end %>

                    <% if can? :edit, Dispatcher  %>
                        <%= link_to edit_dispatcher_path( dispatcher ), title: 'Edit Dispatcher',
                                    class: 'btn btn-small btn-warning' do %>
                            <i class="icon-pencil"></i>
                        <% end %>
                    <% end %>

                    <% if can?( :delete, Dispatcher ) && !dispatcher.has_scheduled_scans? %>
                        <%= link_to dispatcher, title: 'Delete Dispatcher',
                                    method: :delete, class: 'btn btn-small btn-danger',
                                    data: { confirm: 'Are you sure you want to delete this Dispatcher?' } do %>
                            <i class="icon-trash"></i>
                        <% end %>
                    <% end %>

                    <% if can? :share, dispatcher %>
                        <%= render partial: 'shared/share_form', locals: { model: dispatcher, nolabel: true } %>
                    <% end %>
                </td>
            </tr>
        <% end %>
    </table>
<% else %>
    <p class="alert alert-info">
        There are no dispatchers in the '<%= active_tab.to_s.capitalize %>'
        category at the moment.
    </p>
<% end %>

include/arachni/system/arachni-ui-web/app/views/dispatchers/_tables.js.erb
$("#dispatchers #tables").data( "refresh-url", "<%= escape_javascript dispatchers_path( format: :js, params: params ) %>" );
$('#dispatchers #tables').html( "<%= escape_javascript( render partial: 'tables', formats: :html, locals: { profiles: @dispatchers } ) %>" );

include/arachni/system/arachni-ui-web/app/views/dispatchers/edit.html.erb
<% title "Editing #{@dispatcher.url}" %>
<% breadcrumb_add 'Dispatchers', dispatchers_path %>

<div class="page-header">
    <h1>Editing '<%= @dispatcher %>' Dispatcher</h1>
</div>

<div id="dispatchers">
<%= render 'form' %>
</div>

include/arachni/system/arachni-ui-web/app/views/dispatchers/index.html.erb
<% title "Dispatchers" %>

<div id="dispatchers">
    <div class="page-header">
        <h1>Dispatchers</h1>

        <div class="lead">
            Utilise agents to perform scans originating from remote machines.
        </div>
    </div>

    <% if can? :create, Dispatcher %>
    <p>
        <%= link_to new_dispatcher_path, class: 'btn btn-primary' do %>
            <i class="icon-plus"></i> New Dispatcher
        <% end %>
    </p>
    <% end %>

    <div id="tables"
         data-refresh-url="<%= dispatchers_path( params: params, format: :js ) %>"
         data-refresh-rate="<%= HardSettings.dispatcher_refresh_rate %>"
         data-refresh-type='js'
     >
        <%=  render 'tables' %>
    </div>
</div>

include/arachni/system/arachni-ui-web/app/views/dispatchers/show.html.erb
<% title @dispatcher.url %>
<% breadcrumb_add 'Dispatchers', dispatchers_path %>

<div id="dispatchers">
    <div id="dispatcher"
         data-refresh-url="<%= dispatcher_path( @dispatcher, partial: true ) %>"
         data-refresh-rate="<%= HardSettings.dispatcher_refresh_rate %>"
    >
        <%= render @dispatcher %>
    </div>
</div>