include/arachni/system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

include/arachni/system/arachni-ui-web/app/models/scan_group.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class ScanGroup < ActiveRecord::Base
    belongs_to :owner, class_name: 'User', foreign_key: :owner_id
    has_and_belongs_to_many :scans
    has_and_belongs_to_many :users

    validates_presence_of :name
    validates_uniqueness_of :name, scope: :owner_id

    validates_presence_of :description

    validate :validate_description

    before_save :add_owner_to_subscribers

    def to_s
        name
    end

    private

    def validate_description
        return if ActionController::Base.helpers.strip_tags( description ) == description
        errors.add :description, 'cannot contain HTML, please use Markdown instead'
    end

    def add_owner_to_subscribers
        self.user_ids |= [owner.id]
        true
    end
end

include/arachni/system/arachni-ui-web/app/controllers/scan_groups_controller.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class ScanGroupsController < ApplicationController
    include ScanGroupsHelper
    include ScansHelper

    before_filter :authenticate_user!

    # Watch out, sets @scan_group to an empty group as a fail-safe.
    before_action :set_selected_group, only: [:new, :edit, :create, :update, :destroy]

    before_action :new_scan_group, only: [ :create ]
    before_action :set_scan_group, only: [:edit, :update, :destroy]

    load_and_authorize_resource

    # GET /scan_groups/new
    def new
        respond_to do |format|
            format.js { render '_form_with_list.js' }
        end
    end

    # GET /scan_groups/1/edit
    def edit
        respond_to do |format|
            format.js { render '_form_with_list.js' }
        end
    end

    # POST /scan_groups
    def create
        @scan_group.owner = current_user

        @scan_group = ScanGroup.new if @scan_group.save

        respond_to do |format|
            format.js { render '_form_with_list.js' }
        end
    end

    # PATCH/PUT /scan_groups/1
    def update
        @scan_group = ScanGroup.new if @scan_group.update( strong_params )
        respond_to do |format|
            format.js { render '_form_with_list.js' }
        end
    end

    # DELETE /scan_groups/1
    def destroy
        @scan_group.destroy
        @scan_group = ScanGroup.new

        respond_to do |format|
            format.js { render '_form_with_list.js' }
        end
    end

    private

    def new_scan_group
        @scan_group = ScanGroup.new( strong_params )
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_scan_group
        @scan_group = ScanGroup.find( params[:id] )
    end

    def set_selected_group
        prepare_scan_group_tab_data
        @group = ScanGroup.find_by_id( params[:selected_group_id] ) if params[:selected_group_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def strong_params
        params.require( :scan_group ).permit( :name, :description, { user_ids: [] } )
    end
end

include/arachni/system/arachni-ui-web/app/helpers/scan_groups_helper.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module ScanGroupsHelper
    def prepare_scan_group_tab_data
        @scan_group  = ScanGroup.new
        @scan_groups = Hash.new([])

        @scan_groups['yours']  = current_user.own_scan_groups
        @scan_groups['shared'] = current_user.shared_scan_groups

        if current_user.admin?
            @scan_groups['others'] = current_user.others_scan_groups
        end
    end
end

include/arachni/system/arachni-ui-web/app/views/scan_groups/_form.html.erb
<%= simple_form_for( @scan_group, remote: true ) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
        <%= f.input :name, label: false, placeholder: '(Required) Name' %>
        <%= f.input :description, label: false, placeholder: '(Required) Description' %>

        <% if User.count > 1 %>

            <%=
                if @scan_group.id
                    exclude = [@scan_group.owner]
                else
                    exclude = [current_user]
                end
                f.association :users, label: 'Share with:',
                              collection: User.all - exclude
            %>
        <% end %>
    </div>

    <button type="submit" class="btn btn-small btn-inverse">
        <% if @scan_group.id %>
            Update group
        <% else %>
            <i class="icon-plus"></i>
            New group
        <% end %>
    </button>

    <input type="hidden" id="selected_group_id" name="selected_group_id"
           value="<%= @group.try( :id ) %>"/>

    <% if @scan_group.errors.any? || @scan_group.id %>
        <%= link_to new_scan_group_path( selected_group_id: @group.try( :id ) ),
                    class: 'btn btn-small', remote: true, onclick: 'loading();' do %>
            Cancel
        <% end %>
    <% end %>
<% end %>

include/arachni/system/arachni-ui-web/app/views/scan_groups/_form_with_list.html.erb
<%
   if local_assigns[:path_method].is_a? Symbol
       path_method = method( local_assigns[:path_method] )
   elsif local_assigns[:path_method].nil?
       path_method = method( :scans_path )
   end
%>

<h3>Groups</h3>

<div id="scan-groups-list">
    <%= render partial: 'scan_groups/list_with_tabs', locals: { path_method: path_method } %>
</div>

<hr/>

<div id="scan-group-form">
    <%= render partial: 'scan_groups/form' %>
</div>

include/arachni/system/arachni-ui-web/app/views/scan_groups/_form_with_list.js.erb
$("#scan-groups-sidebar").html( "<%= escape_javascript render( 'scan_groups/form_with_list.html' ) %>" );

include/arachni/system/arachni-ui-web/app/views/scan_groups/_list.html.erb
<%

   if local_assigns[:path_method].is_a? Symbol
       path_method = method( local_assigns[:path_method] )
   elsif local_assigns[:path_method].nil?
       path_method = method( :scans_path )
   end

   show_owner = !!local_assigns[:show_owner]
%>

<div class="row-fluid scan-groups-list">
    <% if can? :manage, groups.first %>
        <div class="span3">
            <ul class="unstyled group">

                <% groups.each do |group| %>
                    <li>
                        <%= link_to scan_group_path( group,
                                                     selected_group_id: @group.try( :id ) ),
                                    method: :delete, remote: true,
                                    onclick: 'loading();', confirm: 'Delete this group?' do %>
                            <i class="icon-remove"></i>
                        <% end %>

                        <%= link_to edit_scan_group_path( group,
                                                          selected_group_id: @group.try( :id ) ),
                                    remote: true, onclick: 'loading();' do %>
                            <i class="icon-pencil"></i>
                        <% end %>
                    </li>

                    <% if show_owner %>
                        <li>&nbsp;</li>
                    <% end %>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="span6">
        <ul class="nav nav-list">
            <% groups.each do |group| %>
                <li
                <%= 'class="active"'.html_safe if group == @group %>
                >
                    <%= link_to path_method.call( params.merge( format: nil, group_id: group.id ) ),
                                onclick: 'loading();', remote: true do %>
                        <%= group %> (<%= group.scans.size %>)
                    <% end %>
                </li>

                <% if show_owner %>
                    <li class="muted">
                        <small>By <%= group.owner %></small>
                    </li>
                <% end %>
            <% end %>
        </ul>
    </div>
</div>

include/arachni/system/arachni-ui-web/app/views/scan_groups/_list_with_tabs.html.erb
<%
   if local_assigns[:path_method].is_a? Symbol
       path_method = method( local_assigns[:path_method] )
   elsif local_assigns[:path_method].nil?
       path_method = method( :scans_path )
   end
%>

<% if @group %>
    <p>
        You are seeing scans of the <strong><%= @group.name %></strong> group:
    </p>

    <blockquote>
        <%= m @group.description %>

        <% if @group.owner != current_user %>
            <small><%= @group.owner %></small>
        <% end %>
    </blockquote>

    <p>
        Members:
        <%= @group.users.map { |u| link_to u, user_path( u ) }.join( ', ' ).html_safe %>
    </p>
    <hr/>

    <p>
        <%= link_to path_method.call( group_id: false ), onclick: 'loading();',
                    class: 'btn btn-small btn-info btn-clear', remote: true do %>
            Clear filter
        <% end %>
    </p>
<% end %>

<ul class="nav nav-tabs" id="scan-group-tabs"
    data-table-container="table-container">

    <% if @scan_groups['yours'].size == 0 %>
        <li class="disabled">
            <a href="#" onclick="return false;" title="Yours">
                <i class="icon-user"></i>
                [<%= @scan_groups['yours'].size %>]
            </a>
        </li>
    <% else %>
        <li class="active">
            <a href="#scan-groups-yours" data-toggle="tab" title="Yours">
                <i class="icon-user"></i>
                [<%= @scan_groups['yours'].size %>]
            </a>
        </li>
    <% end %>


    <% if @scan_groups['shared'].size == 0 %>
        <li class="disabled">
            <a href="#" onclick="return false;" title="Shared">
                <i class="icon-share-alt"></i>
                [<%= @scan_groups['shared'].size %>]
            </a>
        </li>
    <% else %>
        <li>
            <a href="#scan-groups-shared" data-toggle="tab"  title="Shared">
                <i class="icon-share-alt"></i>
                [<%= @scan_groups['shared'].size %>]
            </a>
        </li>
    <% end %>

    <% if current_user.admin? %>
        <% if @scan_groups['others'].size == 0 %>
            <li class="disabled">
                <a href="#" onclick="return false;" title="Others'">
                    <i class="icon-group"></i>
                    [<%= @scan_groups['others'].size %>]
                </a>
            </li>
        <% else %>
            <li>
                <a href="#scan-groups-others" data-toggle="tab"  title="Others'">
                    <i class="icon-group"></i>
                    [<%= @scan_groups['others'].size %>]
                </a>
            </li>
        <% end %>
    <% end %>
</ul>

<div class="tab-content">
    <div id="scan-groups-yours" class="tab-pane active in">
        <% if @scan_groups['yours'].any? %>
            <p class="muted">Your groups.</p>

            <%= render partial: 'scan_groups/list',
                       locals: { path_method: path_method, groups: @scan_groups['yours'] } %>
        <% else %>
            <p class="alert alert-info">
                You haven't created any groups.
            </p>
        <% end %>
    </div>

    <div id="scan-groups-shared" class="tab-pane">
        <p class="muted">Groups others have shared with you.</p>

        <%= render partial: 'scan_groups/list',
                   locals: { path_method: path_method, groups: @scan_groups['shared'], show_owner: true } %>
    </div>

    <% if current_user.admin? %>
        <div id="scan-groups-others" class="tab-pane">
            <p class="muted">Everyone else's groups.</p>

            <%= render partial: 'scan_groups/list',
                       locals: { path_method: path_method, groups: @scan_groups['others'], show_owner: true } %>
        </div>
    <% end %>
</div>

<script type="text/javascript">
    // The tabs will be restored when the document is ready anyways but the
    // slight delay makes it look bad.
    updatePage();
</script>

include/arachni/system/arachni-ui-web/app/views/scan_groups/edit.html.erb
<h1>Editing scan_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @scan_group %> |
<%= link_to 'Back', scan_groups_path %>

include/arachni/system/arachni-ui-web/app/views/scan_groups/index.html.erb
<h1>Listing scan_groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Owner</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scan_groups.each do |scan_group| %>
    <tr>
      <td><%= scan_group.name %></td>
      <td><%= scan_group.description %></td>
      <td><%= scan_group.owner_id %></td>
      <td><%= link_to 'Show', scan_group %></td>
      <td><%= link_to 'Edit', edit_scan_group_path(scan_group) %></td>
      <td><%= link_to 'Destroy', scan_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Scan group', new_scan_group_path %>

include/arachni/system/arachni-ui-web/app/views/scan_groups/new.html.erb
<h1>New scan_group</h1>

<%= render 'form' %>

include/arachni/system/arachni-ui-web/app/views/scan_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @scan_group.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scan_group.description %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @scan_group.owner_id %>
</p>


<%= link_to 'Edit', edit_scan_group_path(@scan_group) %> |
<%= link_to 'Back', scan_groups_path %>