include/arachni/system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

include/arachni/system/arachni-ui-web/app/helpers/scans_helper.rb
=begin
    Copyright 2013-2017 Sarosys LLC <http://www.sarosys.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module ScansHelper

    def prepare_tables_data
        params[:filter_finished]  ||= 'yours'
        params[:filter_active]    ||= 'yours'
        params[:filter_suspended] ||= 'yours'

        @counts = {
            active: {},
            finished: {},
            suspended: {}
        }
        %w(yours shared others).each do |type|
            begin
                @counts[:active][type] = scan_filter( type ).active.count
                @counts[:active]['total'] ||= 0
                @counts[:active]['total']  += @counts[:active][type]

                @counts[:finished][type] = scan_filter( type ).finished.count
                @counts[:finished]['total'] ||= 0
                @counts[:finished]['total']  += @counts[:finished][type]

                @counts[:suspended][type] = scan_filter( type ).suspended.count
                @counts[:suspended]['total'] ||= 0
                @counts[:suspended]['total']  += @counts[:suspended][type]
            rescue
            end
        end

        @active_scans = scan_filter( params[:filter_active] ).active.
                            page( params[:active_page] ).
                            per( HardSettings.active_scan_pagination_entries ).
                            order( 'id DESC' )

        @finished_scans = scan_filter( params[:filter_finished] ).roots.finished.
                            page( params[:finished_page] ).
                            per( HardSettings.finished_scan_pagination_entries ).
                            order( 'id DESC' )

        @suspended_scans = scan_filter( params[:filter_suspended] ).roots.suspended.
                            page( params[:suspended_page] ).
                            per( HardSettings.finished_scan_pagination_entries ).
                            order( 'id DESC' )
    end

    def prepare_schedule_data
        params[:filter] ||= 'yours'

        @counts = {}
        %w(yours shared others).each do |type|
            begin
                @counts[type] = scan_filter( type ).scheduled.count

                @counts['total'] ||= 0
                @counts['total']  += @counts[type]
            rescue => e
                ap e
                ap e.backtrace
            end
        end

        @scans = scan_filter( params[:filter] ).scheduled.
            page( params[:active_page] ).
            per( HardSettings.scheduled_scan_pagination_entries ).
            order( 'id DESC' )
    end

    def scan_filter( filter )
        filter ||= 'yours'

        group_scans =   if (group_id = params[:group_id].to_i) > 0
                            if current_user.admin?
                                if (@group = ScanGroup.find_by_id( params[:group_id] ))
                                    @group.scans
                                else
                                    current_user.scans
                                end
                            else
                                @group = current_user.scan_groups.find_by_id( params[:group_id] )

                                if @group
                                    @group.scans
                                else
                                    current_user.scans
                                end
                            end
                        else
                            current_user.scans
                        end

        case filter
            when 'yours'
                group_scans.where( owner_id: current_user.id )

            when 'shared'
                s = group_scans.where( 'owner_id != ?', current_user.id )

                if current_user.admin?
                    s.where( 'id in (?)', current_user.scans.pluck( :id ) )
                else
                    s
                end

            when 'others'
                raise 'Unauthorised!' if !current_user.admin?

                ids = group_scans.where( 'owner_id != ?', current_user.id ).
                        where( 'id in (?)', current_user.scans.pluck( :id ) ) +
                    group_scans.select( :id ).
                        where( owner_id: current_user.id )

                rest_ids = if group_id
                               group_scans
                           else
                               Scan
                           end.select( :id )

                Scan.where( id: rest_ids - ids )
        end
    end

    def issues_to_graph_data( issues )
        graph_data = {
            severities:       {
                Arachni::Severity::HIGH.to_sym          => 0,
                Arachni::Severity::MEDIUM.to_sym        => 0,
                Arachni::Severity::LOW.to_sym           => 0,
                Arachni::Severity::INFORMATIONAL.to_sym => 0
            },
            issues:           {},
            elements:         {
                Arachni::Element::Form.type              => 0,
                Arachni::Element::Form::DOM.type         => 0,
                Arachni::Element::Link.type              => 0,
                Arachni::Element::Link::DOM.type         => 0,
                Arachni::Element::Cookie.type            => 0,
                Arachni::Element::Cookie::DOM.type       => 0,
                Arachni::Element::Header.type            => 0,
                Arachni::Element::LinkTemplate.type      => 0,
                Arachni::Element::LinkTemplate::DOM.type => 0,
                Arachni::Element::GenericDOM.type        => 0,
                Arachni::Element::XML.type               => 0,
                Arachni::Element::JSON.type              => 0,
                Arachni::Element::UIForm.type            => 0,
                Arachni::Element::UIForm::DOM.type       => 0,
                Arachni::Element::UIInput.type           => 0,
                Arachni::Element::UIInput::DOM.type      => 0,
                Arachni::Element::Body.type              => 0,
                Arachni::Element::Path.type              => 0,
                Arachni::Element::Server.type            => 0
            }
        }

        total_severities = 0
        total_elements   = 0

        issues.each.with_index do |issue, i|
            graph_data[:severities][issue.severity.downcase.to_sym] += 1
            total_severities += 1

            graph_data[:issues][issue.name] ||= 0
            graph_data[:issues][issue.name] += 1

            graph_data[:elements][issue.vector_type.to_sym] += 1
            total_elements += 1
        end

        graph_data
    end

    def response_times_to_alert( time )
        time = time.to_f

        if time >= 0.7
            [ 'alert-error',
              'The server takes too long to respond to the scan requests,' +
                  ' this will severely diminish performance.']
        elsif (0.35..0.7).include?( time )
            [ 'alert-warning',
              'Server response times could be better but nothing to worry about yet.' ]
        else
            [ 'alert-success',
              'Server response times are excellent.' ]
        end
    end

    def concurrent_requests_to_alert( request_count, max )
        max = max.to_i
        request_count = request_count.to_i

        if request_count >= max
            [ 'alert-success',
              'HTTP request concurrency is operating at the allowed maximum.']
        elsif ((max/2)..max).include?( request_count )
            [ 'alert-warning',
              "HTTP request concurrency had to be throttled down (from the " +
                  "maximum of #{max}) due to high server response times, " +
                  'nothing to worry about yet though.' ]
        else
            [ 'alert-error',
              'HTTP request concurrency has been drastically throttled down ' +
                  "(from the maximum of #{max}) due to very high server" +
                  " response times, this will severely decrease performance."]
        end
    end
end

include/arachni/system/arachni-ui-web/app/views/scans/_edit_button_dropdown.html.erb
<% show_as_revision ||= false %>
<% if can? :edit, scan %>
    <%= render partial: 'scan_schedule_form', locals: { scan: scan, nodisplay: true } %>

    <% if !show_as_revision %>
        <%= render partial: 'scan_group_form', locals: { scan: scan, nodisplay: true } %>
        <%= render partial: 'shared/share_form', locals: { model: scan, nodisplay: true } %>
    <% end %>

    <div class="btn-group">
        <%= link_to edit_scan_path( scan ), title: 'Edit',
                    class: 'btn btn-small btn-warning' do %>
            <i class="icon-pencil"></i>
        <% end %>

        <% if !show_as_revision %>
        <button class="btn btn-small btn-warning dropdown-toggle"
                data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul id="scan-edit-button-dropdown-<%= scan.id %>" class="dropdown-menu">
            <% if User.count > 1 && can?( :share, scan ) %>
                <li>
                    <a href="#shareScan<%= scan.id %>" title="Share scan"
                       role="button" data-toggle="modal">
                        <i class="icon-share"></i>

                        <% if (shared_with = scan.users.size - 1) > 0 %>
                      <span title="Shared with <%= pluralize shared_with, 'more user' %>."
                            class="label"><%= shared_with %></span>
                        <% end %>

                        Share
                    </a>
                </li>
            <% end %>

            <% if !scan.finished? && can?( :update, scan ) %>
                <li>
                    <a href="#updateScanSchedule_<%= scan.id %>"
                       title="Update schedule"
                       role="button" data-toggle="modal">
                        <i class="icon-calendar"></i>
                        Edit schedule
                    </a>
                </li>
            <% end %>

            <% if current_user.scan_groups.any? && can?( :update, scan ) %>
                <li>
                    <a href="#updateScanGroup_<%= scan.id %>"
                       title="Update group memberships"
                       role="button" data-toggle="modal">
                        <i class="icon-folder-close-alt"></i>
                        Edit group memberships
                    </a>
                </li>
            <% end %>

        </ul>
        <% end %>
    </div>
<% end %>

include/arachni/system/arachni-ui-web/app/views/scans/_scan_group_form.html.erb
<% if current_user.scan_groups.any? && can?( :update, scan ) %>
    <script type="text/javascript">
        selector = '#updateScanGroup_<%= scan.id %>'

        if( !$(selector).is( ':visible' ) ) {
            refreshModal = true;

            // Remove previous nodes from the DOM.
            $(selector).remove();
        } else {
            refreshModal = false;
        }
    </script>

    <% if !local_assigns[:nodisplay] %>
        <a href="#updateScanGroup_<%= scan.id %>" title="Update group memberships"
           role="button" class="btn btn-small btn-inverse" data-toggle="modal">
            <i class="icon-folder-close-alt"></i>
            <%= 'Update group memberships' if !local_assigns[:nolabel] %>
        </a>
    <% end %>

    <div id="updateScanGroup_<%= scan.id %>" class="modal hide fade"
         tabindex="-1" role="dialog">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&#10006;</button>
            <h3>Join:</h3>
        </div>

        <%= simple_form_for( scan, url: update_memberships_scan_path( scan ) ) do |f| %>
            <div class="modal-body">
                <%= f.error_notification %>
                <%= f.association :scan_groups, collection: current_user.scan_groups,
                                  label: '', as: :check_boxes,
                                  label_method: lambda { |grp|
                                      s  = "#{grp.name}"
                                      s += " (by #{grp.owner})" if current_user != grp.owner
                                      s
                                  }
                %>

            </div>
            <div class="modal-footer">
                <%= f.button :submit, class: 'btn btn-small btn-primary', value: 'Share' %>
                <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
            </div>
        <% end %>
    </div>

    <script type="text/javascript">
        // If we have a scan table then we're probably inside it and since
        // the table will keep being updated by AJAX we must move the modal dialog
        // out of it otherwise it'll keep vanishing with each AJAX refresh.
        if( refreshModal ) {
            // Move the new one out of the table.
            $('#scans').parent().before( $(selector) );
        }
    </script>
<% end %>

include/arachni/system/arachni-ui-web/app/views/scans/_scan_sidebar.html.erb
<ul class="nav nav-list">
    <li class="nav-header">
        Toggle visibility of
    </li>

    <li id="comments-link-container">
        <a class="toggle-comments" data-toggle="collapse"
           href="#comments">
            <i class="icon-comments"></i>

                    <span title="The scan has <%= pluralize @scan.comments.size, 'comment' %>."
                          class="label hide total-comments-counter">
                        <%= @scan.comments.size %>
                    </span>

                    <span title="The scan has new comments."
                          class="hide label label-info new-comments-counter">
                    </span>

            Comments
        </a>
    </li>

    <% if @scan.running? %>
    <li id="toggle-statistics">
        <a href="#statistics" data-toggle="collapse"
           title="Toggle statistics visibility" role="button">
            <i class="icon-list-alt"></i>

            Statistics
        </a>
    </li>
    <% end %>
</ul>

<% if @scan.root_revision.has_revisions? %>
    <div id="revisions-nav-list">
        <%= render 'revisions_nav_list' %>
    </div>
<% end %>

<ul class="nav nav-list">
    <li class="divider"></li>

    <li class="nav-header">
        Actions
    </li>

    <% if User.count > 1 && can?( :share, @scan ) %>
        <li>
            <a href="#shareScan<%= @scan.id %>" title="Share scan"
               role="button" data-toggle="modal">
                <i class="icon-share"></i>

                <% if (shared_with = @scan.users.size - 1) > 0 %>
                      <span title="Shared with <%= pluralize shared_with, 'more user' %>."
                            class="label"><%= shared_with %></span>
                <% end %>

                Share
            </a>

            <%= render partial: 'shared/share_form', locals: { model: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if !@scan.suspended? && !@scan.finished? && can?( :update, @scan ) %>
        <li>
            <a href="#updateScanSchedule_<%= @scan.id %>"
               title="Update schedule"
               role="button" data-toggle="modal">
                <i class="icon-calendar"></i>
                Edit schedule
            </a>

            <%= render partial: 'scan_schedule_form', locals: { scan: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if current_user.scan_groups.any? && can?( :update, @scan ) %>
        <li>
            <a href="#updateScanGroup_<%= @scan.id %>"
               title="Update group memberships"
               role="button" data-toggle="modal">
                <i class="icon-folder-close-alt"></i>
                Edit group memberships
            </a>

            <%= render partial: 'scan_group_form', locals: { scan: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if can?( :update, @scan ) %>
        <li>
            <a href="<%= edit_scan_path @scan %>"
               title="Edit this scan's details"
               role="button">
                <i class="icon-edit"></i>
                Full edit
            </a>
        </li>
    <% end %>

    <% if !@scan.suspended? && @scan.finished? && !@scan.overview? && @scan.report %>
        <li id="download-report">
            <i class="icon-download-alt"></i>
            Download report as:

            <%
               reports_links = reports_with_outfile.map do |shortname, (name, desc)|
                   link_to name, report_scan_path( format: shortname ),
                           rel: 'tooltip', title:  desc, data: { 'no-turbolink' => true }
               end
            %>

            <ul class="nav nav-list">
                <% reports_links.each do |l| %>
                    <li>
                        <%= l %>
                    </li>
                <% end %>
                <li>
                    <%=
                        link_to 'AFR', report_scan_path( format: 'afr' ),
                                rel: 'tooltip', title:  'Arachni Framework Report',
                                data: { 'no-turbolink' => true }
                    %>
                </li>
            </ul>
        </li>
    <% end %>
</ul>

include/arachni/system/arachni-ui-web/app/views/scans/_table_buttons.html.erb
<%
   show_as_revision ||= false
   repeat             = local_assigns[:repeat].nil? ? true : local_assigns[:repeat]
%>

<% if can? :read, scan %>
    <%= link_to !show_as_revision && scan.has_revisions? ? scan_path( scan, overview: true ) : scan,
                title: 'Show scan', class: 'btn btn-small btn-info' do %>
        <i class="icon-eye-open"></i>
    <% end %>
<% end %>

<%= render partial: 'edit_button_dropdown', locals: { scan: scan, show_as_revision: show_as_revision } %>

<% if scan.active? %>
    <% if can? :pause, scan %>
        <% if scan.paused? %>
            <%= link_to resume_scan_path( scan, render: :index ), title: 'Resume scan',
                        method: :patch, class: 'btn btn-small btn-success',
                        remote: true,
                        data: { confirm: 'Are you sure you want to resume the scan?' } do %>
                <i class="icon-play-circle"></i>
            <% end %>

        <% else %>
            <%= link_to pause_scan_path( scan, render: :index ), title: 'Pause scan',
                        method: :patch, class: 'btn btn-small btn-warning',
                        remote: true,
                        data: { confirm: 'Are you sure you want to pause the scan?' } do %>
                <i class="icon-pause"></i>
            <% end %>
        <% end  %>
    <% end  %>

    <% if scan.scanning? && scan.spawns == 0 && can?( :suspend, scan ) %>
        <%= link_to suspend_scan_path(scan),
                    remote: true,
                    title:  'Suspend scan', method: :patch, class: 'btn btn-small',
                    data:   { confirm: 'Are you sure you want to suspend the scan?' } do %>
            <i class="icon-eject"></i>
        <% end %>
    <% end %>

    <% if can? :abort, scan %>
        <%= link_to abort_scan_path( scan, render: :index ), title: 'Abort scan',
                    method: :patch, class: 'btn btn-small btn-danger',
                    remote: true,
                    data: { confirm: 'Are you sure you want to abort the scan?' } do %>
            <i class="icon-stop"></i>

        <% end %>
    <% end %>

    <% if can? :update, scan %>
        <%= render partial: 'scan_schedule_form', locals: { scan: scan, nodisplay: true } %>
    <% end %>

    <% if !show_as_revision %>
        <%= render partial: 'scan_group_form', locals: { scan: scan, nodisplay: true } %>
        <%= render partial: 'shared/share_form', locals: { model: scan, nodisplay: true } %>
    <% end %>
<% elsif scan.suspended? %>

    <%= render 'restore_button', scan: scan %>

    <% if show_as_revision && can?( :share, scan ) %>
        <%= render partial: 'scan_group_form', locals: { scan: scan, nodisplay: true } %>
        <%= render partial: 'shared/share_form', locals: { model: scan, nodisplay: true } %>
    <% end %>

<% else %>
    <% if can? :delete, scan %>
        <%= link_to scan, title: 'Delete scan', method: :delete,
                    class: 'btn btn-small btn-danger', remote: true,
                    data: { confirm: 'Are you sure you want to delete this scan?' } do %>
            <i class="icon-trash"></i>
        <% end %>
    <% end %>

    <% if repeat && !show_as_revision && can?( :repeat, scan ) && scan.profile %>
        <%= link_to new_revision_scan_path( scan ), title: 'Repeat scan',
                    class: 'btn btn-small btn-success' do %>
            <i class="icon-repeat"></i>
        <% end %>
    <% end %>

    <% if show_as_revision && can?( :share, scan ) %>
        <%= render partial: 'scan_group_form', locals: { scan: scan, nodisplay: true } %>
        <%= render partial: 'shared/share_form', locals: { model: scan, nodisplay: true } %>
    <% end %>
<% end %>

include/arachni/system/arachni-ui-web/app/views/scans/_table_row.html.erb
<%
   show_as_revision ||= false

   filter = "filter_#{type}"

   yours = (params[filter] == 'yours')

   class_if_revision = !treat_as_running && (show_as_revision || scan.revision?) ? 'revision' : ''
   class_if_revision << ' root-with-revisions' if scan.root_with_revisions?
%>

<tr <%= if scan.paused?
            "class=\"warning #{class_if_revision}\" title=\"Scan is paused.\"".html_safe
        elsif scan.aborted?
            "class=\"warning #{class_if_revision}\" title=\"Scan was aborted.\"".html_safe
        elsif scan.error?
            "class=\"error #{class_if_revision}\" title=\"Scan encountered a fatal error.\"".html_safe
        else
            "class=\"#{class_if_revision}\"".html_safe
        end
    %>

    <% if scan.root_with_revisions? %>
        <%= "onclick=\"$('#revision-table-container-#{scan.id}').collapse('toggle')\"".html_safe %>
    <% end %>
>

    <% if !treat_as_running && show_as_revision %>
        <td>
            &mdash;
        </td>
    <% end %>

    <td>
        <% if can? :read, scan %>
            <% if !scan.error_messages.to_s.empty? %>
                <%= link_to errors_scan_path( scan, format: :txt ),
                            title: 'This scan has encountered errors.',
                            class: 'label label-important',
                            rel: 'tooltip', data: { placement: 'left' } do %>
                    <i class="icon-exclamation-sign icon-white"></i>
                <% end %>
            <% end %>
        <% end %>

        <% if !show_as_revision %>
            <% if scan.any_scheduled? %>
                <a href="#"
                   rel="tooltip" class="label label-info"
                   data-original-title="Scheduled">
                    <i class="icon-calendar"></i>
                </a>
            <% end %>

            <% if scan.any_recurring? %>
                <a href="#"
                   rel="tooltip" class="label label-info"
                   data-original-title="Recurring">
                    <i class="icon-time"></i>
                </a>
            <% end %>

            <% if treat_as_running && scan.revision? %>
                <a href="#"
                   rel="tooltip" class="label label-info"
                   data-original-title="Revision">
                    <i class="icon-repeat"></i>
                </a>
            <% end %>

            <% if scan.root_with_revisions? %>
                <a href="#revision-table-container-<%= scan.id %>"
                   data-toggle="collapse"
                   rel="tooltip" class="label label-info"
                   data-original-title="Has revisions, click to toggle visibility.">
                    <i class="icon-repeat"></i>
                    <i class="icon-sort-down"></i>
                </a>
            <% end %>
        <% end %>

        <%= link_to scan.url, scan.url %>
    </td>
    <td class="hidden-phone">
        <% if scan.profile %>
            <%= link_to scan.profile.name, scan.profile %>
        <% else %>
            (Deleted)
        <% end %>
    </td>
    <td class="hidden-phone">
        <% if (!show_as_revision && scan.has_revisions?) %>
        N/A
        <% else %>
            <%= scan.type.to_s.capitalize %>
            <% if scan.dispatcher %>
                (<%= link_to scan.dispatcher.url, scan.dispatcher %>)
            <% end %>
        <% end %>
    </td>

    <% if treat_as_running %>
        <td class="hidden-phone"><%= scan.status.to_s.capitalize %></td>
    <% end %>

    <td>
        <%= !show_as_revision && scan.has_revisions? ? scan.revisions_issue_count : scan.issue_count %>
    </td>

    <% if treat_as_running %>
        <td class="hidden-phone"><%= scan.sitemap_size %></td>
        <td class="hidden-phone"><%= Arachni::Utilities.seconds_to_hms scan.runtime %></td>
    <% else %>
        <td class="hidden-phone">
            <% if !show_as_revision && scan.has_revisions? %>
                N/A
            <% else %>
                <%= l scan.started_at %>
            <% end %>
        </td>

        <td <%= 'class="hidden-phone"'.html_safe if !yours %>>
            <% if scan.suspended? %>
              <%= l scan.suspended_at %>
            <% else %>
                <% if (!show_as_revision && scan.has_revisions?) || !scan.finished_at %>
                    N/A
                <% else %>
                    <%= l scan.finished_at %>
                <% end %>
            <% end %>
        </td>
    <% end %>

    <% if !yours %>
        <td>
            <% if scan.owner == current_user %>
                <span class="label">You</span>
            <% else %>
                <%= link_to scan.owner, user_path( scan.owner ) %>
            <% end %>
        </td>
    <% end %>

    <td class="hidden-phone">
        <% if !show_as_revision && scan.has_revisions? %>
            N/A
        <% else %>
            <%= (cs = scan.comments.size) > 1 ? cs : 'None yet' %>
        <% end %>
    </td>

    <td>
        <%= render partial: 'table_buttons',
                   locals: {
                           scan:             scan,
                           treat_as_running: treat_as_running,
                           show_as_revision: show_as_revision
                   } %>
    </td>
</tr>

<% if !show_as_revision && scan.root_with_revisions? %>
    <tr class="revision-table-container">
        <td class="revision-table-container" colspan="8">
            <div id='revision-table-container-<%= scan.id %>' class="collapse">
                <table class="table table-striped table-hover table-condensed">

                    <%= render partial: 'table_headings', locals: {
                            treat_as_running:   treat_as_running,
                            contains_revisions: true,
                            yours:              yours,
                            type:               type
                    } %>

                    <% scan.revisions_with_root.finished.each do |revision| %>
                        <%= render partial: 'table_row',
                                   locals: {
                                        scan:             revision,
                                        treat_as_running: treat_as_running,
                                        show_as_revision: true,
                                        type:             type
                                   } %>
                    <% end %>
                </table>
            </div>
        </td>
    </tr>
<% end %>

include/arachni/system/arachni-ui-web/app/views/scans/errors.text.erb
<%= @scan.error_messages.html_safe %>

include/arachni/system/arachni-ui-web/app/views/scans/index.html.erb
<% title "Scans" %>

<% add_to_sidebar do %>
    <div id="scan-groups-sidebar">
        <%= render 'scan_groups/form_with_list' %>
    </div>
<% end %>

<div id="scans">
    <div class="page-header">
        <h1>Scans</h1>

        <div class="lead">
            Start, manage and stay up to date on your scans.
        </div>
    </div>

    <p>
        <%= link_to new_scan_path, class: 'btn btn-primary' do %>
            <i class="icon-plus"></i> New Scan
        <% end %>

        <%= link_to schedule_scans_path, class: 'btn btn-inverse' do %>
            <i class="icon-calendar"></i> Schedule
        <% end %>

          <a href="#scan-import" title="Import a scan via a report"
             role="button" class="btn btn-inverse" data-toggle="modal">
            <i class="icon-upload-alt"></i> Import
        </a>

      <%= render partial: 'import' %>
    </p>

    <div id="revision-form-modal" class="modal hide fade"
         tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
    </div>

    <div id="tables"
         data-refresh-url="<%= scans_path( format: :js, params: params ) %>"
         data-refresh-rate="<%= HardSettings.scan_refresh_rate %>"
         data-refresh-type='js'
    >
        <%= render 'tables' %>
    </div>

</div>